language: node_js

node_js:
- stable

install:
- yarn install

script:
- yarn run build
- yarn run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
